### ISSUE TITLE
JDK 9 support on opentracing-agent

### ISSUE THREAD

**Issue by johnpoth** [opentracing-contrib/java-agent#18]
When running the opentracing-agent on JDK 9 I am getting:

```
org.jboss.byteman.agent.Transformer : unexpected error injecting trigger for rule apache-camel: Install OpenTracing tracer into class org.apache.camel.impl.DefaultCamelContext
java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
        at org.jboss.byteman.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.jboss.byteman.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.jboss.byteman.agent.check.BytecodeChecker.<init>(BytecodeChecker.java:39)
        at org.jboss.byteman.agent.Transformer.getClassChecker(Transformer.java:943)
        at org.jboss.byteman.agent.TransformContext.listInterfaces(TransformContext.java:570)
```

Which I think is because the java-agent shades byteman v 3.0.6 which doesn't support Java 9. I haven't found a workaround yet.

To reproduce, run tests in https://github.com/apache/camel/tree/master/components/camel-opentracing.

Thanks!

**Comment by objectiser** [comment]
Byteman 4 supports JDK9, but still at Beta3 - will try it out this week to see if fixes the issue.

**Comment by objectiser** [comment]
I've been in communication with the ByteMan lead, who had found some issues with ByteMan 4 - however after sorting those out, there appears to be a limitation currently in JDK9 which causes problems with the java.net rules. Details can be found here: http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-April/012267.html

Once we have an answer on this, we can decide how best to proceed.
